sudo: false

language: php
php:
  # - master
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

git:
  depth: 1

addons:
  apt:
    packages:
    - valgrind
    - gdb

env:
  global:
    - LD_LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LD_LIBRARY_PATH
    - LIBRARY_PATH="$TRAVIS_BUILD_DIR/build/lib":$LIBRARY_PATH
    - C_INCLUDE_PATH="$TRAVIS_BUILD_DIR/build/include"
    - CFLAGS="-g3 -O0 -Wall -fvisibility=hidden"
    - REPORT_EXIT_STATUS=1
    - PATH="${HOME}/bin:${PATH}"
    - RE2C_VERSION="1.1.1"
    - ZEPHIR_PARSER_VERSION="v1.1.2"
    - DEFAULT_ZFLAGS="-Wnonexistent-function -Wnonexistent-class -Wunused-variable"
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.3'
    # - php: 'master'

cache:
  apt: true
  ccache: true
  timeout: 604800
  directories:
    - $HOME/.ccache
    - $HOME/.composer/cache
    - $HOME/.local/opt/re2c
    - $HOME/.cache/re2c

before_install:
  - if [[ ! -z "${GH_TOKEN}" ]]; then composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"; fi;
  - export PHP_MAJOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(`phpenv which php` -r 'echo phpversion();' | cut -d '.' -f 2)"
  - ulimit -c unlimited -S
  - phpenv config-add ./unit-tests/ci/999-default.ini

install:
  - composer install $DEFAULT_COMPOSER_FLAGS
  - ./unit-tests/ci/install-re2c $RE2C_VERSION
  - ./unit-tests/ci/install_zephir_parser.sh
  - ./install

before_script:
  - $(phpenv which php) compiler.php help
  - $(phpenv which php) compiler.php generate $DEFAULT_ZFLAGS
  - $(phpenv which php) compiler.php stubs
  - $(phpenv which php) compiler.php api
  - ./unit-tests/ci/install-test-ext.sh

script:
  - ./unit-tests/ci/run-unit-tests.sh
  - ./unit-tests/ci/memcheck.sh

jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      script:
        - vendor/bin/phpcs --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 Library/ unit-tests/Extension/ unit-tests/Zephir/
    - stage: Compiller testing
      php: 7.2
      compiler: clang
      env:
        - CC=clang
      before_script:
        - $(phpenv which php) compiler.php generate $DEFAULT_ZFLAGS
        - ./unit-tests/ci/install-test-ext.sh
      script:
        - ./unit-tests/ci/memcheck.sh
    - stage: Benchmark
      php: 7.2
      before_script:
        - $(phpenv which php) compiler.php generate $DEFAULT_ZFLAGS
        - ./unit-tests/ci/install-test-ext.sh
      script:
        - phpenv config-rm xdebug.ini || true
        - $(phpenv which php) unit-tests/microbench.php

after_success:
  - if [[ ! -z "${CODECOV_TOKEN}" ]]; then bash <(curl -s https://codecov.io/bash); fi;

after_failure:
  - ./unit-tests/ci/after_failure.sh

notifications:
  email: false
