language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_install:
 - git submodule --quiet update --init --recursive
 - ./unit-tests/ci/before_install.sh

install:
 - composer --prefer-source install
 - wget -c https://github.com/squizlabs/PHP_CodeSniffer/releases/download/2.0.0a2/phpcs.phar

before_script:
 - mkdir -p build/coverage
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"
 - $(phpenv which php) compiler.php generate
 - $(phpenv which php) compiler.php stubs
 - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"; phpize && ./configure --silent --enable-test && make -j2 && sudo make install && phpenv config-add ../unit-tests/ci/test.ini)
 - ulimit -c unlimited || true

script:
 - php phpcs.phar --standard=PSR2 --report=emacs --extensions=php --warning-severity=0 src/ unit-tests/Extension/ unit-tests/Zephir/
 - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes phpunit --debug --coverage-clover="build/logs/clover.xml" --coverage-text="php://stdout"

after_script:
 - vendor/bin/coveralls -v --exclude-no-stmt

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
