language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - ./unit-tests/ci/install_prereqs.sh

before_script:
 - git submodule --quiet update --init --recursive
 - sudo apt-get -qq install valgrind
 - ./install
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"
 - $(phpenv which php) compiler.php generate
 - (cd ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall -fvisibility=hidden"; phpize && ./configure --silent --enable-test && make -j2 && sudo make install && phpenv config-add ../unit-tests/ci/test.ini)
 - ulimit -c unlimited || true

script:
 - phpcs --standard=PSR2 --report=emacs --extensions=php Library
 - valgrind --read-var-info=yes --error-exitcode=1 --fullpath-after= --track-origins=yes $(phpenv which php) ./unit-tests/run_tests.php

after_failure:
 - sudo apt-get -qq install gdb
 - ./unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
