sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

git:
  depth: 1

branches:
  only:
    - master
    - development

addons:
  apt:
    packages:
      - gdb
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/.local/opt/re2c
    - $HOME/.cache/re2c
    - $HOME/.cache/php-psr

env:
  global:
    - CFLAGS="-g -O0 -Wall -fvisibility=hidden"
    - RE2C_VERSION="1.1.1"
    - ZEPHIR_PARSER_VERSION="v1.1.3"
    - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"
    - REPORT_COVERAGE=1
    - PHPUNIT_DONT_EXIT=0
    - PHPUNIT_CONF=phpunit.xml.dist
    - BOX_VERSION=3.1.2
    - PATH="${HOME}/bin:${PATH}"

before_install:
  - '[[ -z "${GH_TOKEN}" ]] || composer config github-oauth.github.com ${GH_TOKEN}; echo "Configured Github token"'
  - export PHP_MAJOR="$(php -r 'echo phpversion();' | cut -d '.' -f 1)"
  - export PHP_MINOR="$(php -r 'echo phpversion();' | cut -d '.' -f 2)"
  - export PHP_VERNUM="$(php-config --vernum)"
  - ulimit -c unlimited -S
  - phpenv config-add ./unit-tests/ci/999-default.ini
  - echo "$TRAVIS_PHP_VERSION"

install:
  - ./unit-tests/ci/install-zephir-parser.sh
  - ./unit-tests/ci/install-re2c.sh $RE2C_VERSION
  - ./unit-tests/ci/install-php-psr.sh
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - ./unit-tests/ci/install-test-ext.sh

before_script:
  # see: https://github.com/sebastianbergmann/phpunit/pull/3359
  - '[[ "${PHP_VERNUM}" -lt 70300 ]] || export USE_ZEND_ALLOC=1 PHPUNIT_CONF=phpunit-no-coverage.xml.dist'

script:
  - |
      php \
        -d extension=ext/modules/test.so \
        unit-tests/phpunit \
        -c ${PHPUNIT_CONF} \
        --testsuite "Extension Test Suite"
  - |
      php \
        -d extension=ext/modules/test.so \
        unit-tests/phpunit \
        -c ${PHPUNIT_CONF} \
        --testsuite "Zephir Test Suite"
jobs:
  include:
    - stage: Static Code Analysis
      php: 7.2
      env:
        - REPORT_COVERAGE=0
      script:
        - vendor/bin/phpcs
    - stage: Compiller testing
      php: 7.2
      compiler: clang
      env:
        - CC=clang
        - REPORT_COVERAGE=0
      script:
        - |
            php \
              -d extension=ext/modules/test.so \
              unit-tests/phpunit \
              -c ${PHPUNIT_CONF} \
              --testsuite "Extension Test Suite"
    - stage: Packaging Test
      php: 7.2
      env:
        - REPORT_COVERAGE=0
      install:
        - ./unit-tests/ci/install-zephir-parser.sh
        - ./unit-tests/ci/install-re2c.sh $RE2C_VERSION
        - ./unit-tests/ci/install-php-psr.sh
        - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
        - mkdir -p ${HOME}/bin
        - |
            wget \
              "https://github.com/humbug/box/releases/download/${BOX_VERSION}/box.phar" \
              --quiet \
              -O "${HOME}/bin/box"
        - chmod +x "${HOME}/bin/box"
        - ./package/packer
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - ./zephir.phar compile
        - |
            php \
              -d extension=ext/modules/test.so \
              unit-tests/phpunit \
              -c ${PHPUNIT_CONF} \
              --testsuite "Extension Test Suite"
    - stage: Benchmark
      php: 7.2
      env:
        - REPORT_COVERAGE=0
      before_script:
        - phpenv config-rm xdebug.ini || true
      script:
        - php -d extension=ext/modules/test.so unit-tests/microbench.php

after_success:
  - ./unit-tests/ci/after-success.sh

after_failure:
  - ./unit-tests/ci/after-failure.sh

notifications:
  email: false
