sudo: false

language: php
php:
  - 'master'
  - '7.3'
  - '7.2'
  - '7.1'
  - '7.0'
  - '5.6'

git:
  depth: 1

addons:
  apt:
    packages:
      - gdb
      - lcov

matrix:
  fast_finish: true
  allow_failures:
    - php: 'master'

cache:
  apt: true
  timeout: 604800
  directories:
    - $HOME/.composer/cache
    - $HOME/.local/opt

env:
  global:
    - RE2C_VERSION="1.1.1"
    - ZEPHIR_PARSER_VERSION="v1.1.3"
    - REPORT_COVERAGE=1
    - BOX_VERSION=3.1.2
    - PATH="${HOME}/bin:${PATH}"

before_install:
  - if [ ! -z "${GITHUB_TOKEN}" ]; then composer config github-oauth.github.com ${GITHUB_TOKEN}; echo "Add Github token"; fi
  - ulimit -c unlimited -S
  - mkdir -p ${HOME}/bin
  - phpenv config-add .ci/999-default.ini
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - .ci/install-prereqs.sh
  - .ci/install-re2c.sh $RE2C_VERSION
  - flags="--ansi --prefer-dist --no-interaction --optimize-autoloader --no-suggest --no-progress"
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ]; then composer config platform.php 5.6.33; echo "Preparing to deploy"; fi
  - travis_retry composer install $flags
  - if [ "$(php-config --vernum)" -ge 70100 ]; then .ci/packer; echo "Build PHAR"; fi
  - if [ "$(php-config --vernum)" -ge 70100 ]; then ln -s $(pwd)/zephir.phar ${HOME}/bin/zephir; echo "Build PHAR"; fi
  - if [ "$(php-config --vernum)" -lt 70100 ]; then ln -s $(pwd)/zephir ${HOME}/bin/zephir; echo "Use source"; fi

before_script:
  - .ci/build-test-ext.sh

script:
  - zephir --ansi
  - ./vendor/bin/phpcs
  - php -d extension=ext/modules/test.so unit-tests/phpunit

after_success:
  - .ci/after-success.sh
  - echo "$TRAVIS_CMD"
  - if [ "${CODECOV_TOKEN}${TRAVIS_PHP_VERSION}" != "5.6" ]; then bash <(curl -s https://codecov.io/bash); fi

notifications:
  email: false

before_deploy:
  - git config --global user.name cicdbot
  - git config --global user.email team@zephir-lang.com

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: zephir.phar
  skip_cleanup: true
  draft: true
  name: "$(zephir --dumpversion)"
  on:
    tags: true
    php: '7.2'
  repo: phalcon/zephir
