language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_install:
 - ./test/unit-tests/ci/install_prereqs.sh

before_script:
 - git submodule --quiet update --init --recursive
 - sudo apt-get -qq install valgrind
 - ./install -c
 - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/usr/local/lib"
 - zephir init test
 - (cd test; zephir install)
 - phpenv config-add ./test/unit-tests/ci/test.ini
 - ulimit -c unlimited || true

script:
 - ./test/unit-tests/run_tests

after_failure:
 - sudo apt-get -qq install gdb
 - ./test/unit-tests/ci/after_failure.sh

notifications:
  email:
    - andres@phalconphp.com
    - eduar@phalconphp.com
